<a href="https://colab.research.google.com/github/tarunsharma1999/SummertrainingML/blob/master/StartingWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arrry=np.array([1,2,3,4])

In [0]:
type(arrry)

In [0]:
arrry2=np.array([1,2,3,4])

In [0]:
arrry*arrry2

In [0]:
# array mathmatics (same dimensions):- 
arrry+arrry2


In [0]:
#squarring a array
arrry**2

In [0]:
#2dimension array
x=np.array([ [1,2,3], [1,2,3], [2,3,4] ])
x

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [0]:
x[0][1]*2

4

In [0]:
#to print dimensions
x.shape

(3, 3)

In [0]:
#from 0 - 1. last no excluded!
x[0:2]

array([[1, 2, 3],
       [1, 2, 3]])

In [0]:
#to process particular column
x[0:,1]

array([2, 2, 3])

In [0]:
x[0:,0:2]

array([[1, 2],
       [1, 2],
       [2, 3]])

In [0]:
#to process random columns, 0th and 2th column
x[0:,[0,2]]

array([[1, 3],
       [1, 3],
       [2, 4]])

In [0]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [0]:
y=np.array([[1,9,7] ,[3,2,8],[4,5,6],[2,9,0]])
y

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [0]:
y[0:,2]

array([7, 8, 6, 0])

In [0]:
y.reshape(6,2)

array([[1, 9],
       [7, 3],
       [2, 8],
       [4, 5],
       [6, 2],
       [9, 0]])

In [0]:
np.ones((5,2))
zero=np.zeros((3,6),dtype=int)
zero


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [0]:
l=np.full((4,5),9)
l

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])